### ISSUE TITLE
Demo doesn't work - pre trained model missing in the repo.

### ISSUE THREAD

**Issue by naik-amey** [letatanu/DeepHomography#1]
I don't think you have pushed the pre-trained model in the repo. That's the reason your demo doesn't work.

**Comment by letatanu** [comment]
In README, I gave the link to download the pre-trained model. 
You can get it from [here](https://drive.google.com/file/d/1ZnmlPu1NeXXMk6NHiP7fegzXM117eb15/view?usp=sharing).

**Comment by naik-amey** [comment]
Sorry my bad, I missed that. Thanks, @letatanu! I had to make a small tweak since I am using a CPU-only machine. Thought of mentioning it here. 

```
    if os.path.isfile(resultModelFile):
        try:
            if device.type == 'cpu':
                model.load_state_dict(torch.load(resultModelFile, map_location=torch.device('cpu')))
            else:
                model.load_state_dict(torch.load(resultModelFile))
        except:
            print("Cannot load the saved model")
```
